In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset("iris")

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df = df[df["species"]!="setosa"]
df

     sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
..            ...          ...           ...          ...         ...
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

[100 rows x 5 columns]

In [5]:
# (mapping)converting the values into 0 and 1

df["species"] = df["species"].map({"versicolor":0, "virginica":1})
df.head()

    sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4        0
51           6.4          3.2           4.5          1.5        0
52           6.9          3.1           4.9          1.5        0
53           5.5          2.3           4.0          1.3        0
54           6.5          2.8           4.6          1.5        0

In [6]:
# Spliting dataset into Dependent and Independent Variables

x = df[["sepal_length","sepal_width", "petal_length", "petal_width"]]
y = df[["species"]]

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [8]:
from sklearn.linear_model import LogisticRegression

lr_classifier = LogisticRegression()

In [10]:
lr_classifier.fit(x_train, y_train)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [14]:
y_pred = lr_classifier.predict(x_test)

In [15]:
x_test

     sepal_length  sepal_width  petal_length  petal_width
133           6.3          2.8           5.1          1.5
80            5.5          2.4           3.8          1.1
106           4.9          2.5           4.5          1.7
74            6.4          2.9           4.3          1.3
66            5.6          3.0           4.5          1.5
73            6.1          2.8           4.7          1.2
52            6.9          3.1           4.9          1.5
77            6.7          3.0           5.0          1.7
78            6.0          2.9           4.5          1.5
63            6.1          2.9           4.7          1.4
149           5.9          3.0           5.1          1.8
142           5.8          2.7           5.1          1.9
126           6.2          2.8           4.8          1.8
64            5.6          2.9           3.6          1.3
50            7.0          3.2           4.7          1.4
71            6.1          2.8           4.0          1.3
53            5.5          2.3           4.0          1.3
79            5.7          2.6           3.5          1.0
111           6.4          2.7           5.3          1.9
129           7.2          3.0           5.8          1.6

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cm = confusion_matrix(y_pred, y_test)
cm

array([[12,  1],
       [ 1,  6]], dtype=int64)

In [19]:
score = accuracy_score(y_pred, y_test)
score

0.9

In [21]:
cr = classification_report(y_pred, y_test)
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.92      0.92        13
           1       0.86      0.86      0.86         7

    accuracy                           0.90        20
   macro avg       0.89      0.89      0.89        20
weighted avg       0.90      0.90      0.90        20